version: '3.8'

services:
  client:
    stdin_open: true
    container_name: frontend
    build: ./client
    volumes:
      - ./client:/app

  api:
    container_name: node
    restart: always
    build: ./server
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - ./server:/app
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  db:
    container_name: postgresdb
    image: postgres
    ports:
      - '5433:${POSTGRES_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
 data: {}
